#!/bin/bash

#
#------------------------------
#
# Import settings
#

. ./settings.sh

SOURCE_DIR=$1

[ -z $SUPPRESS_PLUGINS ] && SUPPRESS_PLUGINS=''

echo "Suppress plugins: ${SUPRESS_PLUGINS}"

/usr/local/bin/cmake ../$SOURCE_DIR -DTEST_PLUGINS=0 -DINCLUDE_PLUGINS=0 ${SUPRESS_PLUGINS} -DSUPPRESS_PY3EMBED=ON -DINCLUDE_PY3EMBED=OFF -DCMAKE_BUILD_TYPE=$PERF_BUILD_TYPE -DMAKE_DOCS=0 -DUSE_CPPUNIT=1 -DINCLUDE_SPARK=0 -DSUPPRESS_SPARK=1 -DSPARK=0 -DGENERATE_COVERAGE_INFO=0 -DUSE_LIBXSLT=ON -DXALAN_LIBRARIES= -DMYSQL_LIBRARIES=/usr/lib64/mysql/libmysqlclient.so  -DMYSQL_INCLUDE_DIR=/usr/include/mysql -DMAKE_MYSQLEMBED=1 -DECLWATCH_BUILD_STRATEGY=SKIP 

